[build]
  command = "node --max-old-space-size=4096 ./node_modules/@angular/cli/bin/ng build --configuration production"
  publish = "dist/sparrow-food/browser"

[build.environment]
  NODE_VERSION = "20.x"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
