[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build:ssr"

[deploy]
startCommand = "node --max-old-space-size=2048 dist/sparrow-food/server/main.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3